name: Vehicle Service CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write
  security-events: write

concurrency:
  group: vehicle-service-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: FleetOps-Project-Devops/fleetops-github-workflows/.github/workflows/java-ci.yml@main
    with:
      service_name: fleetops-vehicle-service
      java_version: "21"
      dockerfile_path: Dockerfile
      image_name: fleetops-vehicle-service
      docker_username: johann2003
      sonar_project_key: fleetops-vehicle-service
      run_sonar: ${{ github.ref_name == 'develop' || github.ref_name == 'main' }}
      run_snyk: ${{ github.ref_name == 'develop' || github.ref_name == 'main' }}
      push_image: ${{ github.event_name == 'push' && (github.ref_name == 'develop' || github.ref_name == 'main') }}
      image_tags: ""
    secrets: inherit
