name: Vehicle Service CD

on:
  workflow_run:
    workflows: ["Vehicle Service CI"]
    types: [completed]
    branches:
      - develop
      - main

concurrency:
  group: vehicle-service-cd-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  cd-dev:
    name: CD - Dev Deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    permissions:
      contents: write
    uses: FleetOps-Project-Devops/fleetops-github-workflows/.github/workflows/cd-dev.yml@main
    with:
      service-name: vehicle-service
      ci-workflow-name: Vehicle Service CI
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MANIFEST_REPO: ${{ secrets.MANIFEST_REPO }}

  cd-prod:
    name: CD - Prod Deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    permissions:
      contents: write
    uses: FleetOps-Project-Devops/fleetops-github-workflows/.github/workflows/cd-prod.yml@main
    with:
      service-name: vehicle-service
      ci-workflow-name: Vehicle Service CI
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MANIFEST_REPO: ${{ secrets.MANIFEST_REPO }}
