CREATE TABLE IF NOT EXISTS vehicles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_number       VARCHAR(20) NOT NULL UNIQUE,
    model                VARCHAR(100) NOT NULL,
    brand                VARCHAR(100) NOT NULL,
    type                 VARCHAR(50) NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    current_mileage      INTEGER NOT NULL DEFAULT 0,
    last_service_date    DATE,
    next_service_date    DATE,
    next_service_mileage INTEGER,
    insurance_expiry     DATE,
    assigned_driver_id   VARCHAR(100),
    created_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    version              BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vehicle_telemetry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id        BIGINT NOT NULL,
    vehicle_number    VARCHAR(20) NOT NULL,
    driver_name       VARCHAR(100),
    latitude          DOUBLE PRECISION NOT NULL,
    longitude         DOUBLE PRECISION NOT NULL,
    speed             INTEGER NOT NULL DEFAULT 0,
    engine_temp       INTEGER,
    status            VARCHAR(20) NOT NULL DEFAULT 'IDLE' CHECK (status IN ('EN_ROUTE', 'IDLE', 'SPEEDING', 'BREAKDOWN')),
    route_description VARCHAR(200),
    recorded_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_telemetry_vehicle_id ON vehicle_telemetry (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_recorded_at ON vehicle_telemetry (recorded_at);
